### ISSUE TITLE
Unique ID mismatch if resource name was changed

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/cloudshell-shell-standards#14]
Hi,

If the resource name was changed the Unique ID would be changed as well.
We need to think of adjusting Unique ID generation.

**Comment by kalsky** [comment]
right. the unique id should be something that is not changing if you move the sub-resource between slots or between devices.
these should usually be serial numbers, mac addresses (if they are not allowed to be changed), etc.

**Comment by Costya-Y** [comment]
Hi @kalsky 
> these should usually be serial numbers, mac addresses (if they are not allowed to be changed), etc.
Well, it appears that these data could be changed as well.
But we will investigate this issue.

Thank you,
Costya

**Comment by Costya-Y** [comment]
I think we have a solution here.
We will need to keep the original resource name somewhere in the metadata of the resource and use it to generate a Unique ID.

It's obviously a temporary workaround.

**Comment by saklar13** [comment]
Done. We calculate unique id using Cloudshell resource id
